# docker-compose.yaml

---
x-airflow-common:
  &airflow-common

  build: .
  image: custom-airflow:latest

  env_file:
    - ${ENV_FILE_PATH:-.env}

  environment:
    &airflow-common-env

    AIRFLOW__CORE__EXECUTOR: CeleryExecutor

    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql+psycopg2://airflow:airflow@postgres/airflow

    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0

    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}

    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'

    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'

    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'

    AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW__API_AUTH__JWT_SECRET:-airflow_jwt_secret}

    AIRFLOW__API_AUTH__JWT_ISSUER: ${AIRFLOW__API_AUTH__JWT_ISSUER:-airflow}

    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'

    AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./config:/opt/airflow/config
    - ./plugins:/opt/airflow/plugins
    - ./sql_scripts:/opt/airflow/sql_scripts

  user: "${AIRFLOW_UID:-50000}:0"

  depends_on:
    &airflow-common-depends-on

    redis:
      condition: service_healthy

    postgres:
      condition: service_healthy

services:

  postgres:

    image: postgres:16

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s

    restart: always

  redis:

    image: redis:7.2-bookworm

    expose:
      - 6379

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s

    restart: always

  airflow-apiserver:

    <<: *airflow-common

    command: api-server

    ports:
      - "8080:8080"

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/monitor/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    restart: always

    depends_on:
      <<: *airflow-common-depends-on

      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:

    <<: *airflow-common

    command: scheduler

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    restart: always

    depends_on:
      <<: *airflow-common-depends-on

      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:

    <<: *airflow-common

    command: dag-processor

    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"'
        ]

      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    restart: always

    depends_on:
      <<: *airflow-common-depends-on

      airflow-init:
        condition: service_completed_successfully

  airflow-worker:

    <<: *airflow-common

    command: celery worker

    environment:
      <<: *airflow-common-env

      DUMB_INIT_SETSID: "0"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
        ]

      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    restart: always

    depends_on:
      <<: *airflow-common-depends-on

      airflow-apiserver:
        condition: service_healthy

      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:

    <<: *airflow-common

    command: triggerer

    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"'
        ]

      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    restart: always

    depends_on:
      <<: *airflow-common-depends-on

      airflow-init:
        condition: service_completed_successfully

  airflow-init:

    <<: *airflow-common

    command:
      - bash
      - -c
      - |
        mkdir -p /opt/airflow/logs
        mkdir -p /opt/airflow/dags
        mkdir -p /opt/airflow/plugins
        mkdir -p /opt/airflow/config

        chown -R "${AIRFLOW_UID}:0" /opt/airflow/

        airflow db migrate

        airflow users create \
          --username airflow \
          --password airflow \
          --firstname Airflow \
          --lastname Admin \
          --role Admin \
          --email airflow@example.com

    environment:
      <<: *airflow-common-env

      _AIRFLOW_DB_MIGRATE: 'true'

      _AIRFLOW_WWW_USER_CREATE: 'true'

      _AIRFLOW_WWW_USER_USERNAME: airflow

      _AIRFLOW_WWW_USER_PASSWORD: airflow

    user: "0:0"
volumes:
  postgres-db-volume:
